# -*- coding: utf-8 -*-
"""Crime_Pred

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmTP6PU3_AW1j6pABWQqgYNl5wnnFMzX
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from prophet import Prophet

from google.colab import drive
drive.mount('/content/drive')

path="/content/drive/MyDrive/Crime_Pred/Chicago_Crimes_2012_to_2017.csv"
chicago_df=pd.read_csv(path)
chicago_df.head()

chicago_df.shape

chicago_df.head()

chicago_df.tail(10)

plt.figure(figsize=(12,8))
sns.heatmap(chicago_df.isnull(),cbar=False)

chicago_df.drop(['Unnamed: 0','ID','Case Number','IUCR','X Coordinate','Y Coordinate','Updated On','Year','Ward','Beat','Latitude','Longitude','Year','FBI Code','Community Area','Location','District'],inplace=True,axis=1)

chicago_df.head()

chicago_df.Date = pd.to_datetime(chicago_df.Date,format='%m/%d/%Y %I:%M:%S %p')

chicago_df.Date

chicago_df.index=pd.DatetimeIndex(chicago_df.Date)

chicago_df

chicago_df['Primary Type'].value_counts()

chicago_df['Primary Type'].value_counts().iloc[:15].index

order = chicago_df['Primary Type'].value_counts().iloc[:15].index.drop_duplicates()

chicago_df = chicago_df.reset_index(drop=True)
order = chicago_df['Primary Type'].value_counts().iloc[:15].index.drop_duplicates()
plt.figure(figsize=(12,8))
sns.countplot(y='Primary Type', data=chicago_df, order=order)

plt.figure(figsize=(12,8))
sns.countplot(y='Location Description',data=chicago_df,order=chicago_df['Location Description'].value_counts().iloc[:15].index)

chicago_df = chicago_df.set_index('Date')
chicago_df.resample('YE').size()

plt.plot(chicago_df.resample('Y').size())
plt.title("Crime Count Per Year")
plt.xlabel("Year")
plt.ylabel("Number of crimes")

plt.plot(chicago_df.resample('M').size())
plt.title("Crime Count Per Month")
plt.xlabel("Month")
plt.ylabel("Number of crimes")

plt.plot(chicago_df.resample('Q').size())
plt.title("Crime Count Per Quarter")
plt.xlabel("Quarter")
plt.ylabel("Number of crimes")

chicago_prophet = chicago_df.resample('M').size().reset_index()

chicago_prophet

chicago_prophet.columns=['Date','Crime Count']

chicago_prophet

chicago_prophet_final=chicago_prophet.rename(columns={'Date':'ds','Crime Count':'y'})

chicago_prophet_final

m=Prophet()
m.fit(chicago_prophet_final)

future=m.make_future_dataframe(periods=700)

forecast=m.predict(future)

forecast

figure=m.plot(forecast,xlabel='Date',ylabel='Crime Rate')

figure=m.plot_components(forecast)

